### ISSUE TITLE
Any way to get this with windows support

### ISSUE THREAD

**Issue by Sipherdrakon** [Grandfather-Paradox/paramount-dl#1]
This would be great in python or at the very least batch, any way to make that happen?

**Comment by BrendanoElTaco** [comment]
Would also like windows support

**Comment by Grandfather-Paradox** [comment]
You can run this script on Windows using Cygwin. You have to install [Cygwin](https://www.cygwin.com/install.html), [MKVToolNix](https://www.fosshub.com/MKVToolNix.html), and [MediaInfo](https://mediaarea.net/en/MediaInfo/Download/Windows). You will have to set MKVToolNix, MediaInfo, and youtube-dl in the Windows PATH - you can read about how to do that [here](https://medium.com/@kevinmarkvi/how-to-add-executables-to-your-path-in-windows-5ffa4ce61a53). You might also want to set paramount-dl to avoid having to navigate to its directory every time, but you will still have to navigate to the directory with your links.txt file.

**Comment by mchill** [comment]
Another option to run this on any platform is Docker. I won't go into the details of how to install Docker, but you can do it on Linux, Windows, and Mac.

1. Add this `Dockerfile` to the same directory as `paramount-dl`.
   ```dockerfile
   FROM alpine:latest

   RUN apk update
   RUN apk add bash python3 mkvtoolnix mediainfo
   RUN pip3 install youtube-dl

   WORKDIR /workspace
   COPY paramount-dl /usr/bin/paramount-dl

   ENTRYPOINT ["bash", "/usr/bin/paramount-dl"]
   ```

2. Build the image.
   ```bash
   docker build -t paramount-dl .
   ```

3. Run the script.
   ```bash
   docker run -it --rm -v /path/to/links-txt:/workspace paramount-dl
   ```

**Comment by khthe8th** [comment]
> Another option to run this on any platform is Docker. I won't go into the details of how to install Docker, but you can do it on Linux, Windows, and Mac.
> 
>     1. Add this `Dockerfile` to the same directory as `paramount-dl`.
>        ```dockerfile
>        FROM alpine:latest
>        
>        RUN apk update
>        RUN apk add bash python3 python3-dev py3-pip mkvtoolnix mediainfo gcc g++ make libffi-dev openssl-dev ffmpeg
>        RUN pip3 install youtube-dl pycrypto
>        
>        WORKDIR /workspace
>        COPY paramount-dl /usr/bin/paramount-dl
>        
>        ENTRYPOINT ["bash", "/usr/bin/paramount-dl"]
>        ```
> 
>     2. Build the image.
>        ```shell
>        docker build -t paramount-dl .
>        ```
> 
>     3. Run the script.
>        ```shell
>        docker run -it --rm -v /path/to/dir-with-links-txt:/workspace paramount-dl
>        ```

Hey I know it's a bit old but do you have any idea why I am getting a no such file or directory error? I've got the links.txt setup as required I believe

wc: links.txt: No such file or directory
/usr/bin/paramount-dl: line 80: links.txt: No such file or directory

**Comment by mchill** [comment]
> Hey I know it's a bit old but do you have any idea why I am getting a no such file or directory error? I've got the links.txt setup as required I believe
> 
> wc: links.txt: No such file or directory /usr/bin/paramount-dl: line 80: links.txt: No such file or directory

Sounds like your links.txt file isn't mounted into the container filesystem where it should be. You can check by running:
```bash
docker run -it --rm -v /path/to/dir-with-links-txt:/workspace --entrypoint ls paramount-dl
```
