### ISSUE TITLE
Possible to skip broken links

### ISSUE THREAD

**Issue by BrendanoElTaco** [Grandfather-Paradox/paramount-dl#8]
I have no idea how to code shell, so I'm asking here. Is there a way for it to skip a link if it errors too many times?

**Comment by aforst** [comment]
See my pull request here:
https://github.com/Grandfather-Paradox/paramount-dl/pull/6

It fixes this problem--just copy the code from that, change the number of retries at the top to whatever you want, and it'll stop retrying after that number.
